name: Run Tests

on:
  push:
    branches:
      - main   # Adjust this branch name if you use a different default branch

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for testing

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x   # Adjust the Go version as per your requirement

    - name: Run tests
      run: go test -v ./...
